### ISSUE TITLE
BCM4360: Access Point mode

### ISSUE THREAD

**Issue by ozalexo** [antoineco/broadcom-wl#1]
Hello,

Is it possible to set BCM4360 device (Asus PCI-E AC68) into Access Point mode?
Currently there is no `NL80211_IFTYPE_AP` mode in the list of modes:
 `wdev->wiphy->interface_modes = BIT(NL80211_IFTYPE_STATION) | BIT(NL80211_IFTYPE_ADHOC);`

Thanks in advance.

**Comment by antoineco** [comment]
AFAIK this driver does not support any operating mode other than **IBSS** and **managed**. On my machine `iw list` returns:

```
Wiphy phy0
...
    Supported interface modes:
         * IBSS
         * managed
...
```

Unfortunately I do not own this code base, I just patched it for newer Linux kernel versions. I hope the [`brcm80211`](https://wireless.wiki.kernel.org/en/users/Drivers/brcm80211) driver will support this chipset in the future (PCI ID 14e4:43a0 just for the reference).
