### ISSUE TITLE
Does this driver support AP mode?

### ISSUE THREAD

**Issue by gusarg81** [antoineco/broadcom-wl#19]
Hi,

I don't know if is the right place to ask. Currently I have a TP-LINK Archer T9E PCIE board with BCM4360 ( Broadcom Inc. and subsidiaries BCM4360 802.11ac Wireless Network Adapter (rev 03)) and seems that with the propietary driver AP mode is not available.

I've compiled and installed this one and seems the same thing. Do you know if is a hardware or software problem?

Thanks.

**Comment by antoineco** [comment]
Hi @gusarg81, I remember somebody asked that question some time ago in #1, but the answer was unfortunately _no_. This driver only supports the standard ad-hoc mode.

**Comment by gusarg81** [comment]
Ok, thanks for replying @antoineco.
