### ISSUE TITLE
Linux 5.12.0 gives rfkill: "Cannot get wiphy information"

### ISSUE THREAD

**Issue by koosvriezen** [antoineco/broadcom-wl#20]
The wifi does work despite the warning, it has become very slow with connecting.
Based on [cfg80211: change netdev registration/unregistration semantics](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=linux-5.12.y&id=2fe8ef106238b274c505c480ecf00d8765abf0d8)
I came up with the following patch, which for me at least resolves the issue. Though I'm not sure both netdev register changes are necessary
[wl.diff.txt](https://github.com/antoineco/broadcom-wl/files/6443124/wl.diff.txt)

**Comment by antoineco** [comment]
@koosvriezen thanks for reporting! The patch looks reasonable ✅
